name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # Se met à jour toutes les nuits
  workflow_dispatch: # Permet de le lancer à la main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: timeo-grrd
          BRANCH_NAME: "main"
          UTC_OFFSET: 1
          THEME: dracula
